bind 0.0.0.0
protected-mode yes
port 6379
appendonly yes
save 900 1
save 300 10
save 60 10000
dir /data
appendfsync everysec
maxmemory 512mb
maxmemory-policy allkeys-lru
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
tcp-keepalive 60
databases 16
timeout 0
notify-keyspace-events Ex
latency-monitor-threshold 100
