"""feat: Create DW schemas, data marts, and apply model refinements

Revision ID: 5df623f8d1b8
Revises: b642bda69c3d
Create Date: 2026-08-08 13:28:18.873333

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df623f8d1b8'
down_revision = 'b642bda69c3d'
branch_labels = None
depends_on = None

SCHEMAS = [
    "analytics",
    "suppliers_mart",
    "categories_mart",
    "disability_market_mart",
    "dq_views",
    "lineage_views",
]

VIEWS = {
    "suppliers_mart.v_supplier_performance": """
    CREATE OR REPLACE VIEW suppliers_mart.v_supplier_performance AS
    SELECT
        dp.razon_social,
        dp.rut,
        COUNT(fa.id) AS total_adjudicaciones,
        SUM(fa.monto_adjudicado) AS monto_total_adjudicado,
        AVG(fa.ratio_adjudicacion) AS ratio_adjudicacion_promedio,
        MAX(df.fecha) as ultima_adjudicacion
    FROM dw.fact_adjudicacion fa
    JOIN dw.dim_proveedor dp ON fa.proveedor_key = dp.proveedor_key
    JOIN dw.dim_fecha df on fa.fecha_key = df.fecha_key
    WHERE dp.is_current = true
    GROUP BY 1, 2;
    """,
    "categories_mart.v_category_spending": """
    CREATE OR REPLACE VIEW categories_mart.v_category_spending AS
    SELECT
        dc.nombre as categoria,
        dc.codigo as codigo_categoria,
        SUM(foc.monto_total) AS gasto_total_oc,
        COUNT(foc.id) AS numero_ordenes_compra,
        AVG(foc.monto_total) AS gasto_promedio_oc
    FROM dw.fact_orden_compra foc
    JOIN dw.dim_categoria dc ON foc.categoria_key = dc.categoria_key
    GROUP BY 1, 2;
    """,
    "disability_market_mart.v_disability_contracts": """
    CREATE OR REPLACE VIEW disability_market_mart.v_disability_contracts AS
    SELECT
        fl.licitacion_id,
        flc.nombre,
        flc.descripcion,
        fa.monto_adjudicado,
        dp.razon_social AS proveedor,
        dorg.nombre AS organismo,
        df.fecha AS periodo
    FROM dw.fact_adjudicacion fa
    JOIN dw.fact_licitacion fl ON fa.licitacion_key = fl.id
    JOIN core.licitacion flc ON fl.licitacion_id = flc.codigo
    JOIN dw.dim_proveedor dp ON fa.proveedor_key = dp.proveedor_key
    JOIN dw.dim_organismo dorg ON fa.organismo_key = dorg.organismo_key
    JOIN dw.dim_fecha df ON fa.fecha_key = df.fecha_key
    WHERE dp.is_current = true AND dorg.is_current = true AND flc.nombre ILIKE '%%discapacidad%%';
    """,
}

MATERIALIZED_VIEWS = {
    "analytics.mv_market_monthly": """
    CREATE MATERIALIZED VIEW analytics.mv_market_monthly AS
    SELECT
        DATE_TRUNC('month', df.fecha)::date AS mes,
        COUNT(DISTINCT fl.id) AS total_licitaciones,
        COUNT(DISTINCT fa.id) AS total_adjudicaciones,
        SUM(fa.monto_adjudicado) AS monto_total_adjudicado
    FROM dw.dim_fecha df
    LEFT JOIN dw.fact_licitacion fl ON df.fecha_key = fl.fecha_key
    LEFT JOIN dw.fact_adjudicacion fa ON df.fecha_key = fa.fecha_key
    WHERE df.anio >= 2024
    GROUP BY 1;
    """
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create schemas
    for schema in SCHEMAS:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema};")

    # Alter tables
    op.alter_column('fact_licitacion', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=None,
               schema='dw')
    op.alter_column('fact_oferta', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               schema='dw')
    op.alter_column('fact_adjudicacion', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               schema='dw')
    op.alter_column('fact_orden_compra', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               schema='dw')

    op.create_foreign_key(
        "fk_fact_oferta_licitacion_key", "fact_oferta", "fact_licitacion",
        ["licitacion_key"], ["id"], source_schema='dw', referent_schema='dw'
    )
    op.create_foreign_key(
        "fk_fact_adjudicacion_licitacion_key", "fact_adjudicacion", "fact_licitacion",
        ["licitacion_key"], ["id"], source_schema='dw', referent_schema='dw'
    )

    # Create views and materialized views
    for view_name, view_sql in VIEWS.items():
        op.execute(view_sql)
    
    for mv_name, mv_sql in MATERIALIZED_VIEWS.items():
        op.execute(f"DROP MATERIALIZED VIEW IF EXISTS {mv_name};")
        op.execute(mv_sql)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop views and materialized views
    for view_name in VIEWS:
        op.execute(f"DROP VIEW IF EXISTS {view_name};")

    for mv_name in MATERIALIZED_VIEWS:
        op.execute(f"DROP MATERIALIZED VIEW IF EXISTS {mv_name};")

    # Drop foreign keys
    op.drop_constraint("fk_fact_oferta_licitacion_key", "fact_oferta", schema='dw', type_='foreignkey')
    op.drop_constraint("fk_fact_adjudicacion_licitacion_key", "fact_adjudicacion", schema='dw', type_='foreignkey')
    
    # Revert altered tables (Note: data loss can occur when downgrading from BigInt to Int)
    op.alter_column('fact_licitacion', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               schema='dw')
    op.alter_column('fact_oferta', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               schema='dw')
    op.alter_column('fact_adjudicacion', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               schema='dw')
    op.alter_column('fact_orden_compra', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               schema='dw')

    # Drop schemas
    for schema in SCHEMAS:
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE;")

    # ### end Alembic commands ###
